### PR TITLE
Upgrade PyYaml to 3.13 to support Python 3.7

### PR DESCRIPTION
**Pull request by deepakjois**
PyYaml 3.12 fails to install on Python 3.7

### CODE REVIEW

**Review by emesterhazy — CHANGES_REQUESTED** [review]
Thanks Deepak. Can you change the requirements to `>=` instead of `==`? I think this may help prevent incompatibilities in the future.

**Comment by deepakjois** [comment]
Sure. Do you mean for all the requirements, or just for PyYaml?

**Comment by emesterhazy** [comment]
Initially I was thinking all of the requirements, but let's leave a hard version requirement for genanki since I'm not sure how stable the API is. Everything else I think we can change to `>=`. What do you think?

**Comment by deepakjois** [comment]
Updated the dependencies. Only genanki has a hard `==` version requirement.

**Review by emesterhazy — APPROVED** [review]

**Pull request merged**
